version: '3.8'

services:
  nctu6-unieinfra:
    image: registry.unieai.com/unieverse/uifw-one:2.1
    volumes:
      - /mnt/weights:/mnt/weights
      - /home/nctu6/llm_test:/opt/llm_test
      - /sys:/sys:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /etc/unieai:/etc/unieai
    runtime: nvidia
    cap_add:
      - SYS_ADMIN
    network_mode: host
    environment:
      - NCCL_DEBUG=INFO
    shm_size: 256gb
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "unieai s0410
      --model-path ${MODEL_SERIES}/${MODEL_NAME}
      --host=0.0.0.0
      --port=8999
      --tp=${TP}"
