version: "3.9"
services:
  nctu6-unieinfra:
    image: registry.unieai.com/unieverse/uifw-one:latest
    volumes:
      - /mnt/weights:/mnt/weights
      - /home/nctu6/llm_test:/opt/llm_test
      - /sys:/sys:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /etc/unieai:/etc/unieai
    runtime: nvidia
    cap_add:
      - SYS_ADMIN
    network_mode: host
    environment:
      NCCL_DEBUG: INFO
      MODEL_PATH: ${MODEL_PATH}
      MODEL_NAME: ${MODEL_NAME}
      PORT: ${PORT}
      TP_SIZE: ${TP_SIZE}
    shm_size: 256gb
    ports:
      - "${PORT}:${PORT}"
    entrypoint: bash
    command: /entrypoint_inner.sh