version: "3.9"
services:
  vllm:
    #image: habana-vllm:latest
    image: vllm:habana
    runtime: habana
    privileged: true
    container_name: habana-vllm-for-autotest
    network_mode: host
    volumes:
      - /dev/accel:/dev/accel
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ~/weights:/weights
      - ./:/workspace
      - /tmp/traces:/mnt/traces
      - ./entrypoint_inner.sh:/entrypoint_inner.sh
    ipc: host
    environment:
      HABANA_DEVICE: gaudi3
      DEVICE: gaudi3
      VLLM_TORCH_PROFILER_DIR: /mnt/traces/
      MODEL_OWNER: ${MODEL_OWNER:-/weights/Qwen/Qwen3-0.6B}
      MODEL_NAME: ${MODEL_NAME:-Qwen3-0.6B}
      TP_SIZE: ${TP_SIZE:-1}
      PORT: ${PORT:-8000}
      VLLM_SKIP_WARMUP: ${SKIPWARMUP:-true}
    ports:
      - "${PORT}:${PORT}"
    entrypoint: bash
    command: /entrypoint_inner.sh
    # command: -c "sleep infinity"
