version: "3.9"
services:
  habana-vllm:
    image: vllm:habana
    runtime: habana
    privileged: true
    container_name: habana-vllm-for-autotest
    network_mode: host
    volumes:
      - /dev/accel:/dev/accel
      - ~/.cache/huggingface:/root/.cache/huggingface
      - ${MODEL_PATH:-/weights}:/weights
      - ./:/workspace
      - /tmp/traces:/mnt/traces
      - ./entrypoint.sh:/entrypoint.sh
    ipc: host
    environment:
      HABANA_DEVICE: gaudi3
      DEVICE: gaudi3
      VLLM_TORCH_PROFILER_DIR: /mnt/traces/
      ENGINE: ${ENGINE}
      MODEL_PATH: ${MODEL_PATH:-/weights}
      MODEL_OWNER: ${MODEL_OWNER:-google}
      MODEL_NAME: ${MODEL_NAME:-gemma-3-270m}
      TP_SIZE: ${TP_SIZE:-1}
      PORT: ${PORT:-8999}
      VLLM_SKIP_WARMUP: ${SKIPWARMUP:-true}
    ports:
      - "${PORT}:${PORT}"
    entrypoint: bash
    command: /entrypoint.sh
    # command: -c "sleep infinity"
