version: "3.8"

services:
  genai-perf:
    build:
      context: .          # Dockerfile 所在目錄，這裡是同資料夾
      dockerfile: Dockerfile  # 可省略，如果名字就是 Dockerfile
    network_mode: host
    container_name: unieai-test-s-for-autotest
    volumes:
      - ./entrypoint_inner.sh:/entrypoint_inner.sh
      - ${MODEL_PATH:-/home/unieai2/weights}:/weights
      - ~/results/unieai-test-s:/results/unieai-test-s
      - ../../../scripts:/app/scripts
    entrypoint: bash
    command: /entrypoint_inner.sh
    environment:
      - PYTHONUNBUFFERED=1
      - PORT=${PORT:-8999}
      - MODEL_OWNER=${MODEL_OWNER:-Qwen}
      - MODEL_NAME=${MODEL_NAME:-Qwen3-0.6B}
      - INPUT_TOKENS=${INPUT_TOKENS:-1024}
      - OUTPUT_TOKENS=${OUTPUT_TOKENS:-1024}
      - TP_SIZE=${TP_SIZE:-1}
      - INTERVAL=${INTERVAL:-120000}
      - CONCURRENCY=${CONCURRENCY:-1}
      - RESULT_DIR=/results/unieai-test-s
    restart: "no"
